# Generated by Django 4.2.5 on 2023-12-02 05:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("route_id", models.IntegerField(blank=True, null=True)),
                ("route_long_name", models.TextField(blank=True, null=True)),
                ("agency", models.TextField(blank=True, null=True)),
                ("stop_details", models.TextField(blank=True, null=True)),
                ("is_ac", models.IntegerField(blank=True, null=True)),
                ("fare_matrix", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "all_routes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CancellationTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancel_by", models.JSONField()),
                ("cancellation_fee", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[("std:011", "Delhi"), ("std:080", "Bangalore")],
                        default="std:011",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[("IND", "India")],
                        default="IND",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fulfilment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                (
                    "stops",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), blank=True, null=True, size=None
                    ),
                ),
                ("vehicle", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("descriptor", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=100)),
                ("images", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("tags", models.CharField(max_length=100)),
                ("metadata", models.CharField(max_length=100)),
                (
                    "fulfillment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.fulfilment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title for the site", max_length=127),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.IntegerField(blank=True, null=True)),
                ("stop_name", models.CharField(blank=True, max_length=255, null=True)),
                ("stop_pos", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                ("name", models.CharField(help_text="Some test field", max_length=127)),
            ],
            options={
                "verbose_name": "Test Model",
                "verbose_name_plural": "Test Model",
                "ordering": ("-is_active", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("collected_by", models.CharField(max_length=100)),
                ("params", models.JSONField()),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.billing",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="main.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.billing",
                    ),
                ),
                (
                    "cancellation_terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.cancellationterms",
                    ),
                ),
                (
                    "items",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="main.item"
                    ),
                ),
                (
                    "payments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.city"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[("ONDC:TRV10", "Trv10")],
                        db_index=True,
                        default="ONDC:TRV10",
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("bap_id", models.CharField(db_index=True, max_length=64)),
                ("transaction_id", models.CharField(db_index=True, max_length=64)),
                ("message_id", models.CharField(db_index=True, max_length=64)),
                ("version", models.CharField(db_index=True, max_length=16)),
                (
                    "action",
                    models.CharField(
                        choices=[("search", "Search")],
                        db_index=True,
                        default="search",
                        max_length=16,
                    ),
                ),
                ("bap_uri", models.URLField(db_index=True)),
                ("ttl", models.CharField(db_index=True, max_length=8)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.location"
                    ),
                ),
            ],
            options={
                "ordering": ("-is_active", "-created_at"),
                "abstract": False,
            },
        ),
    ]
