# Generated by Django 4.2.5 on 2023-12-06 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stop",
        ),
        migrations.DeleteModel(
            name="Route",
        ),
    ]
