# Generated by Django 4.2.5 on 2023-12-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_delete_stop_delete_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="domain",
            field=models.CharField(
                choices=[("ONDC:TRV10", "Trv10"), ("ONDC:TRV11", "Trv11")],
                db_index=True,
                default="ONDC:TRV10",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="fulfilment",
            name="stops",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fulfilment",
            name="vehicle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
