# Generated by Django 4.2.5 on 2023-12-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_context_domain_alter_fulfilment_stops_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="action",
            field=models.CharField(
                choices=[
                    ("search", "Search"),
                    ("select", "Select"),
                    ("init", "Init"),
                    ("confirm", "Confirm"),
                    ("update", "Update"),
                ],
                db_index=True,
                default="search",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
