# Generated by Django 4.2.5 on 2023-12-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_context_action_alter_payment_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cancellation_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.cancellationterms",
            ),
        ),
    ]
