# Generated by Django 4.2.5 on 2023-12-17 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_order_cancellation_terms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="context",
            name="location",
        ),
        migrations.RemoveField(
            model_name="location",
            name="city",
        ),
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Context",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
