# Generated by Django 4.2.5 on 2023-12-17 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_context_location_remove_location_city_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
