# Generated by Django 4.2.1 on 2024-05-11 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import main.models.tickets


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_delete_testmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "pnr",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "ticket_status",
                    models.IntegerField(
                        choices=[
                            (1, "Confirmed"),
                            (3, "Pending"),
                            (5, "Cancelled"),
                            (7, "Expired"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "transit_pnr",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "passenger_count",
                    models.IntegerField(
                        default=1, help_text="Number of passengers for this ticket"
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
                (
                    "payment_type",
                    models.IntegerField(
                        choices=[(1, "Prepaid"), (3, "Postpaid"), (5, "Free")],
                        default=1,
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[(1, "Not Completed"), (3, "Completed")], default=1
                    ),
                ),
                ("valid_till", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "discount_percentage",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_description_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "verbose_name": "Ticket Type",
                "verbose_name_plural": "Ticket Types",
            },
        ),
        migrations.CreateModel(
            name="TicketUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("trigger_signal", models.BooleanField(default=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_updates",
                        to="main.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Update",
                "verbose_name_plural": "Ticket Updates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                default=main.models.tickets.TicketType.get_default_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.tickettype",
            ),
        ),
    ]
