# Generated by Django 4.2.1 on 2024-05-20 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_ticket_tickettype_ticketupdate_delete_settings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FareBreakup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "toll",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "convenience_charge",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "convenience_charge_tax",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Please enter calculated value.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "add_on",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "add_on_tax",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Please enter calculated value.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cancellation_chg",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "franchisee_service_charge",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("coupon", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "coupon_discount",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="end_stop_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="route",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="start_stop_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="subscriber_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ticket",
            name="fare",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.farebreakup",
            ),
        ),
    ]
