# Generated by Django 4.2.5 on 2024-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_ticket_active_ticket_created_at_ticket_end_stop_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="subscriber_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
