# Generated by Django 4.2.1 on 2024-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_agency_ticket_is_ac_ticket_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="claim_status",
            field=models.IntegerField(
                choices=[("1", "Claimed"), ("3", "Unclaimed")], default="1"
            ),
        ),
    ]
