# Generated by Django 4.2.1 on 2024-12-26 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models.pass_setup
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_ticket_claim_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "validity_in_days",
                    models.IntegerField(default=1, help_text="Pass validity in days"),
                ),
                (
                    "price",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("item_id", models.CharField(blank=True, max_length=64, null=True)),
                ("provider_id", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "verbose_name": "Pass Type",
                "verbose_name_plural": "Pass Types",
            },
        ),
        migrations.CreateModel(
            name="Pass",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "pnr",
                    models.CharField(
                        db_index=True, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Confirmed"),
                            (3, "Pending"),
                            (5, "Cancelled"),
                            (7, "Expired"),
                        ],
                        db_index=True,
                        default=3,
                        help_text="Type of transit option, like bike, bus, metro etc.",
                    ),
                ),
                (
                    "transit_pnr",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("govt_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "govt_id_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, default=0.0, null=True)),
                ("valid_till", models.DateTimeField(blank=True, null=True)),
                (
                    "claim_status",
                    models.IntegerField(
                        choices=[("1", "Claimed"), ("3", "Unclaimed")], default="3"
                    ),
                ),
                (
                    "pass_type",
                    models.ForeignKey(
                        default=main.models.pass_setup.PassType.get_default_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.passtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Passes",
                "ordering": ("-created_at",),
                "unique_together": {("pnr",)},
            },
        ),
    ]
