# Generated by Django 4.2.1 on 2024-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_passtype_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="pass",
            name="user_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
