# Generated by Django 4.2.1 on 2024-12-27 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_pass_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassFareBreakup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "toll",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "convenience_charge",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "convenience_charge_tax",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Please enter calculated value.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "add_on",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "add_on_tax",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Please enter calculated value.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cancellation_chg",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "franchisee_service_charge",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("coupon", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "coupon_discount",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="pass",
            old_name="photo_url",
            new_name="photo",
        ),
        migrations.RemoveField(
            model_name="pass",
            name="status",
        ),
        migrations.AddField(
            model_name="pass",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.agency",
            ),
        ),
        migrations.AddField(
            model_name="pass",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="pass",
            name="is_ac",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="pass",
            name="pass_status",
            field=models.IntegerField(
                choices=[
                    (1, "Confirmed"),
                    (3, "Pending"),
                    (5, "Cancelled"),
                    (7, "Expired"),
                ],
                db_index=True,
                default=3,
                help_text="Status of the pass",
            ),
        ),
        migrations.AddField(
            model_name="pass",
            name="subscriber_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pass",
            name="fare",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.passfarebreakup",
            ),
        ),
    ]
