# Generated by Django 4.2.1 on 2025-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_passfarebreakup_rename_photo_url_pass_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passtype",
            name="item_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="passtype",
            name="name",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
