# Generated by Django 4.2.1 on 2025-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_passtype_item_id_alter_passtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pass",
            name="photo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
