# Generated by Django 4.2.17 on 2025-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_pass_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="passtype",
            name="pass_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
