# Generated by Django 4.2.17 on 2025-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_passtype_pass_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="passtype",
            name="allowed_documents",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passtype",
            name="is_ac",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="passtype",
            name="is_document_required",
            field=models.BooleanField(default=False),
        ),
    ]
